# Generated by Django 4.0.3 on 2022-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_pic', models.ImageField(upload_to='')),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
